plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'net.fabricmc.fabric-loom' version '1.15.5' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.147' apply false
    id "me.modmuss50.mod-publish-plugin" version "2.2.0"
}

publishMods {
	changelog = providers.environmentVariable("RELEASE_NOTES").getOrElse("*Missing changelog*")
	type = STABLE
	dryRun = providers.environmentVariable("IS_RELEASE").getOrNull() != "true"

	def cfOptions = curseforgeOptions {
		accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
		projectId = providers.gradleProperty("curseforge_project_id")
		minecraftVersions.add(providers.gradleProperty("minecraft_version"))
		client = true
		server = true
	}
	def mrOptions = modrinthOptions {
		accessToken = providers.environmentVariable("MODRINTH_TOKEN")
		projectId = providers.gradleProperty("modrinth_project_id")
		minecraftVersions.add(providers.gradleProperty("minecraft_version"))
		environment = CLIENT_AND_SERVER
	}

	curseforge("curseforgeFabric") {
		from cfOptions
		file project(":fabric")
		modLoaders.add("fabric")
		requires {
			slug = "fabric-api"
		}
	}
	curseforge("curseforgeNeoforge") {
		from cfOptions
		file project(":neoforge")
		modLoaders.add("neoforge")
	}

	modrinth("modrinthFabric") {
		from mrOptions
		file project(":fabric")
		modLoaders.add("fabric")
		requires {
			slug = "fabric-api"
		}
	}
	modrinth("modrinthNeoforge") {
		from mrOptions
		file project(":neoforge")
		modLoaders.add("neoforge")
	}

	github {
		accessToken = providers.environmentVariable("GITHUB_TOKEN").getOrElse("INVALID")
		repository = providers.environmentVariable("GITHUB_REPOSITORY").getOrElse("INVALID")
		commitish = providers.environmentVariable("GITHUB_REF_NAME").getOrElse("main")
		tagName = "v${providers.gradleProperty("version")}"

		allowEmptyFiles = true
	}
	github("githubFabric") {
		accessToken = providers.environmentVariable("GITHUB_TOKEN").getOrElse("INVALID")
		file project(":fabric")

		parent project(":").tasks.named("publishGithub")
	}
	github("githubNeoforge") {
		accessToken = providers.environmentVariable("GITHUB_TOKEN").getOrElse("INVALID")
		file project(":neoforge")

		parent project(":").tasks.named("publishGithub")
	}

	discord {
		webhookUrl = providers.environmentVariable("DISCORD_WEBHOOK_URL").getOrElse("INVALID")
		dryRunWebhookUrl = providers.environmentVariable("DISCORD_WEBHOOK_URL_DRY_RUN")
		username = providers.gradleProperty("mod_name")
		avatarUrl = providers.environmentVariable("ICON_URL").getOrNull()
		content = "${providers.gradleProperty("mod_name")} v${providers.gradleProperty("version")} has been released!"
		setPlatforms(publishMods.platforms.modrinthFabric, publishMods.platforms.modrinthNeoforge)

		style {
			look = "MODERN"
			link = "BUTTON"
		}
	}
}
