# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=2.0.0
group=co.secretonline.tinyflowers
java_version=${JAVA_VERSION}

# Common
minecraft_version=${MINECRAFT_VERSION}
mod_name=Tiny Flowers
mod_author=secret_online
mod_id=tiny_flowers
license=MPL-2.0
credits=secret_online
description=Add tiny variants of all Vanilla flowers.
minecraft_version_range=[${NUMERIC_VERSION},)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=${NEOFORM_VERSION}

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=${FABRIC_API_VERSION}
fabric_loader_version=${FABRIC_LOADER_VERSION}

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=${NEOFORGE_VERSION}
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

enabled_platforms=fabric,neoforge
