name: Update versions
description: Get versions of the game for the build and test workflow

inputs:
  minecraft-version:
    description: Minecraft version to update to. If not supplied, falls back to latest version.
  ignore-mod-dependencies:
    description: Ignore mod dependency versions

outputs:
  has-updates:
    description: Whether there are updates to include
  minecraft-version:
    description: Highest Minecraft version supported
  java-version:
    description: Java version required for this version
  fabric-loader-version:
    description: Version of Fabric loader used by this project
  fabric-api-version:
    description: Version of the Fabric API mod used by this project
  mod-menu-version:
    description: Version of the Mod Menu mod used by this project
  neoforge-version:
    description: Version of the NeoForge used by this project

runs:
  using: "node20"
  main: "index.js"
