name: Update Minecraft Version
run-name: Update Minecraft Version (${{ inputs.minecraft-version || 'latest' }})

on:
  schedule:
    # 6:13 am UTC
    # = 6:13 pm NZST
    - cron: "13 6 * * 5"
  workflow_dispatch:
    inputs:
      minecraft-version:
        description: New Minecraft version
        required: false
        type: string
      branch-only:
        description: Do not create PR
        type: boolean

jobs:
  update-minecraft:
    name: Update Minecraft Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Fetch versions
        id: versions
        uses: SecretOnline/minecraft-actions/get-update-versions@main
        with:
          minecraft-version: ${{ inputs.minecraft-version }}
          user-agent: secret_online/accessible-step (mc@secretonline.co)

      - name: Update gradle.properties
        run: |
          sed -i 's/^java_version=.*/java_version=${{ steps.versions.outputs.java-version }}/' gradle.properties
          sed -i 's/^minecraft_version=.*/minecraft_version=${{ steps.versions.outputs.minecraft-version }}/' gradle.properties
          sed -i 's/^minecraft_version_range=.*/minecraft_version_range=[${{ steps.versions.outputs.numeric-version }},)/' gradle.properties
          sed -i 's/^neo_form_version=.*/neo_form_version=${{ steps.versions.outputs.neoform-version }}/' gradle.properties
          sed -i 's/^neoforge_version=.*/neoforge_version=${{ steps.versions.outputs.neoforge-version }}/' gradle.properties
          sed -i 's/^fabric_version=.*/fabric_version=${{ steps.versions.outputs.fabric-api-version }}/' gradle.properties
          sed -i 's/^fabric_loader_version=.*/fabric_loader_version=${{ steps.versions.outputs.fabric-loader-version }}/' gradle.properties

      - name: Create standalone branch
        if: inputs.branch-only
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git checkout -b auto-update/${{ steps.versions.outputs.minecraft-version }}
          git add gradle.properties
          git commit -m "Update to Minecraft ${{ steps.versions.outputs.minecraft-version }}"
          git push --force origin auto-update/${{ steps.versions.outputs.minecraft-version }}

      - name: Prepare PR body
        if: ${{ !inputs.branch-only }}
        run: |
          cat << 'EOF' > pr-body.md
          This PR contains automated updates from the update-minecraft-version workflow.

          ## Updates

          |Component|Version|
          |---|---|
          |Minecraft|`${{ steps.versions.outputs.minecraft-version }}`|
          |Java|`${{ steps.versions.outputs.java-version }}`|
          |NeoForm|`${{ steps.versions.outputs.neoform-version }}`|
          |NeoForge|`${{ steps.versions.outputs.neoforge-version }}`|
          |Fabric Loader|`${{ steps.versions.outputs.fabric-loader-version }}`|
          |Fabric API|`${{ steps.versions.outputs.fabric-api-version }}`|

          ## Remember to check!

          - This update does not do any remapping.
            - It may not compile.
            - It may still crash at run time.
          EOF

      - name: Create Pull Request
        if: ${{ !inputs.branch-only }}
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.CREATE_PR_PAT }}
          commit-message: "Update to Minecraft ${{ steps.versions.outputs.minecraft-version }}"
          branch: auto-update/${{ steps.versions.outputs.minecraft-version }}
          delete-branch: true
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: "[Auto] Update to Minecraft ${{ steps.versions.outputs.minecraft-version }}"
          body-path: pr-body.md
          add-paths: |
            gradle.properties
